### ISSUE TITLE
Stacked row columns look good, but violate your "no color" principle.

### ISSUE THREAD

**Issue by prahladyeri** [prahladyeri/K2M#4]
Hey Kirill,

I've tried to arrange the rows and cols in a stack arrangement as shown in your video. A colored row/column button looks quite professional, but violates your "no-color" principle. Please let me know if we can make an exception for this one or we use a plain one in this case too. Here is how the colored buttons look (have a look at **OrderID** column):

![row_column_design](https://cloud.githubusercontent.com/assets/5732256/12070482/1c6b4e72-b09d-11e5-8cb3-42c345473468.png)

**Comment by key2market** [comment]
Hi Prahlad, I don't mind the colors if they have a purpose and are professionally looking. I would like to stick to Tableau scheme and color usage. You can use that as a guide if you need to.
