### ISSUE TITLE
Menu item on Row/col buttons to create summary columns. Confirm if the following design is correct.

### ISSUE THREAD

**Issue by prahladyeri** [prahladyeri/K2M#5]
Hey Kirill,

In order to clear my understanding about your exact need (and thus avoid lots of wasted hours later on), I want to clarify this query right away.

On the row/col buttons, I'm planning to add a menu containing all summary operations (`count`, `sum`, `min`, `max`, `average`, etc.) and once you select needed summaries, it will query those from backend `sql` and update chart dynamically. Please confirm if this is what you want (see below screenshot to get an idea of how this looks assuming you clicked on the `ProductID` column):

![row_column_menus](https://cloud.githubusercontent.com/assets/5732256/12070588/ee10d57c-b0a3-11e5-92d6-fb83002361cd.png)

**Comment by key2market** [comment]
Hi Prahlad, yes that is correct. But the Summary needs to be only one selection, not checkboxes. There is one dropdown per measure and one summary per measure. For example. If I group data by country, I may want to COUNT users and get AVERAGE temperature. But I cannot count and average users. There should be only one aggregation/summary per metrics

**Comment by key2market** [comment]
Can we have a small square like in the picture to bring up the menu dropdown?
![screen shot 2016-01-01 at 1 00 03 pm](https://cloud.githubusercontent.com/assets/16460237/12070766/d98d9e3a-b087-11e5-81ae-4877768cf797.png)
![screen shot 2016-01-01 at 1 00 20 pm](https://cloud.githubusercontent.com/assets/16460237/12070767/d98e920e-b087-11e5-9d36-2f25e4251b48.png)

**Comment by prahladyeri** [comment]
> But I cannot count and average users. There should be only one aggregation/summary per metrics

This conflicts with your view on issue no. #6 . There you say say that you want to drag the column multiple times, so as to create multiple summaries per column. Please confirm which view is final?

> Can we have a small square like in the picture to bring up the menu dropdown?

Easily possible using `bootstrap` :+1: . You were saying you want plain white, that's why I didn't make it like that in the first place.

**Comment by 7NXT-kirill** [comment]
If you make it like tableau, I don't mind the colors ;)

**Comment by prahladyeri** [comment]
Sure, I'll try my best to make it like tableau, but tableau is a `Desktop` app, so we may not be able to replicate exact functionality on the web based app. Moreover, its also better to have some originality in design (but at the same time, keep in mind the user's habits to existing design).

**Comment by prahladyeri** [comment]
I've updated the rows and columns functionality as per specs, check out the latest version. The one thing that's remaining is dynamically arranging the line/bar chart according to whether its a row or column, but ignore that for the moment.
I've also followed `tableau` color scheme: `measure` is green, whereas `dimension` is blue. Clicking on a `measure/dimension` gives you the menu to select a `count/min/max/etc.` or change it from `dimension` to `measure` or vice versa.
Test and let me know.

**Comment by key2market** [comment]
Hi Prahlad,
I cannot remove the measures and dimensions that I have already dropped. what if I added a measure and I want to remove it. Can I drag it OUT of Columns / Rows section and it will be removed?

**Comment by key2market** [comment]
Once I clicked on the measure and changed it to dimension. Now it is as dimension, the dropdown still says Dimension -  why does it do that if it is already Dimension?
If it is dimension, it should not have the options to Count/Sum etc available as dimensions cannot be summed up.

**Comment by prahladyeri** [comment]
Firstly, click that measure/dimension, you will find a `Remove` button (similar to how tableau works).

Second change, I'll make accordinlgy

**Comment by key2market** [comment]
Can you remove it by dragging it away from the Row / Columns section?

**Comment by key2market** [comment]
Prahlad, please test your work before you ask me to test it. there are very obvious and weired behaviours  where buttons are dissapearing

**Comment by prahladyeri** [comment]
I was not aware whether that is possible in tableau, is that a tableau feature?

**Comment by key2market** [comment]
I added one dimension, then 2 metrics. Then I removed one and instead two were removed. I try to remove metric but instead both metric and dimension disappear.

**Comment by prahladyeri** [comment]
I tested multiple times, never faced that behavior. What table and fields were they ?

**Comment by key2market** [comment]
You tested expected behavior when you were doing exactly what you built the app to do. QA testing is doing things to intentionally mess up your code. Play with it and try doing most crazy things and you will see unwated behavior

**Comment by prahladyeri** [comment]
Sure, I'll try to catch them and rectify. I expected that the user (you) will try the normal expected functionality first.

**Comment by key2market** [comment]
Here is me playing with it for few minute: https://www.youtube.com/watch?v=a_ApddEW7zE&feature=youtu.be

**Comment by prahladyeri** [comment]
The youtube video says: 

This video is private.
Sorry about that.

**Comment by key2market** [comment]
try now :)

**Comment by prahladyeri** [comment]
What you did was, dragged a `dimension` inside a `measure` instead of dragging inside the white space on the right! I'll fix it soon.

**Comment by prahladyeri** [comment]
> If it is dimension, it should not have the options to Count/Sum etc available as dimensions cannot be summed up.

But what if the user changes mind want this to become a measure instead of dimension? Suppose I dragged `ProductID` and because its a measure it became `count(ProductID)`. Now, I changed it to a dimension, so it changes to `ProductID`. Suppose, again I change my mind and want a count, then all I need to do is click on `count(ProductID)` in the menu, its so easy.

The `sum`, `count`, etc. you are seeing is the measures submenu of the tableau when you right-click a column. Even in tableau, the dimension and all measures are available when you right click it.

**Comment by key2market** [comment]
Hi Prahlad, 
Good Point.
Than for UI improvement could we add nested menu that says Measure like the attached:
Dimension
Measure -> Count, Sum, Min, Max, Avg
Remove

Or just add unclickable heading Measure just above Count in drop down. this will make it a bit clearer and we can leave as is.

![screen shot 2016-01-02 at 3 18 33 pm](https://cloud.githubusercontent.com/assets/16460237/12074734/2aa23786-b164-11e5-864e-ede2d1c29107.png)

**Comment by key2market** [comment]
More on the Issue:
Apparently we can drag Measures to Dimensions box and they become count() and we can also drag Dimensions to Measures box and they become colorful. 
It is ok to drag and drop between those two boxes if:
Like in Tableau, once dimension is dragged into Measures box it is removed from Dimensions box and becomes measure and is treated like measure. And vice versa for Measures.

**Comment by prahladyeri** [comment]
> Or just add unclickable heading Measure just above Count in drop down. this will make it a bit clearer and we can leave as is.

Yup, that could be done.

> Like in Tableau, once dimension is dragged into Measures box it is removed from Dimensions box and becomes measure and is treated like measure. And vice versa for Measures.

OK, this will also be taken care of.

**Comment by prahladyeri** [comment]
Fixed in latest commit, feel free to retest and reopen.
