### ISSUE TITLE
Remember the connection

### ISSUE THREAD

**Issue by key2market** [prahladyeri/K2M#7]
When I leave the page and return I must re-enter the connection credentials. Could we write them to config file for the particular vizualization?

**Comment by prahladyeri** [comment]
On the front-end, there is no such thing as config file. One option is that we can store the connection details in backend `php`, but then it will be fixed for all users. Suppose, `User X` cannot have a different config than `User Y`.

What I recommend is to store it in the JavaScript `localstorage` object. It is secure and the latest `html 5` standard, you can google about it if you want.

**Comment by prahladyeri** [comment]
I believe this one is already solved as of today's commit. Feel free to re-open if you face any issues.
