### ISSUE TITLE
New Line per item

### ISSUE THREAD

**Issue by key2market** [prahladyeri/K2M#9]
For Dimensions, Measures, please have new line for every column.
![screen shot 2016-01-02 at 9 45 04 am](https://cloud.githubusercontent.com/assets/16460237/12073885/85ccb17e-b135-11e5-882d-311f799082f9.png)

**Comment by prahladyeri** [comment]
Sure, I can do that. But did you consider that it will occupy a lot of scree area and if there are many columns, the chart below may not get enough space to display?

**Comment by key2market** [comment]
Lets give both boxes fixed width and height and they will have a scroll when there are too many columns

**Comment by prahladyeri** [comment]
Sure, I'll do that.

**Comment by prahladyeri** [comment]
Fixed this in last commit. Feel free to reopen.

**Comment by key2market** [comment]
Looks good,
Could we add 1 pixel margin between the columns to make it look a bit appealing?

**Comment by prahladyeri** [comment]
Added. Let me know whether one pixel is sufficient or I should increase it.

**Comment by key2market** [comment]
Perfect!
